### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by carlhoerberg** [castle/castle-ruby#11]
Woha, this was a worm can of dependencies! I don't want to pollute my project with activesupport etc. Would prefer if you minimized or didn't use any external dependencies, just use `Net::HTTP`, even if it can a be a pain, but it'll be a lot less pain for your customers. Writing my own custom integration now..

**Comment by carlhoerberg** [comment]
https://gist.github.com/carlhoerberg/d5537dd3990c7e3042942f587801b9cd

**Comment by brissmyr** [comment]
Oh noes, you're not supposed to open the worm can! Your approach makes total sense but I'd still like to have some ORM functionality on top, like the Her gem we're currently using. I'm not too happy with that Gem though so we could write something on our own.

**Comment by TheKidCoder** [comment]
@carlhoerberg I really liked your gist so I simply [gemified](https://rubygems.org/gems/castle-keep) it. I'd be happy to make you a contributor. I do plan on refactoring whats there and adding a few more features, but want to keep the main implementation simple.

**Comment by brissmyr** [comment]
@TheKidCoder really nice! I will submit a PR with some API updates that makes the "Authentication API" easier to work with.

**Comment by brissmyr** [comment]
@carlhoerberg, @TheKidCoder: We just released 2.0.2 which doesn't has any worm can dependencies. Thank you both for the inspiration.
