### ISSUE TITLE
Rails 5 Rc1 Support

### ISSUE THREAD

**Issue by ryanswood** [castle/castle-ruby#12]
I have held off any attempts to upgrade to Rails 5 until I saw a release candidate. Now that the time has come, I am getting dependency conflicts mainly caused by the Her gem which this gem depends on:

```
-> bundle update rails

In Gemfile:
    devise_castle was resolved to 1.3.5, which depends on
      castle-rb (~> 1.2.13) was resolved to 1.2.13, which depends on
        her (~> 0.7) was resolved to 0.8.1, which depends on
          activemodel (<= 4.3.0, >= 3.0.0)
```

The Her gem has not made any progress on supporting Rails 5:
- https://github.com/remiprev/her/issues/392
- https://github.com/remiprev/her/pull/399

What are your thoughts? I am using the Devise_Castle gem and would imagine that other users will eventually want to upgrade to Rails 5 as well.

**Comment by wallin** [comment]
Thanks @ryanswood. Yeah, we definitely want to support Rails5 asap, and it's a shame that the Her gem isn't up to speed.

We'll look into this asap. I think the way forward would be to get rid of Her, since it adds a lot of unnecessary overhead as well

**Comment by ryanswood** [comment]
@wallin Thanks for the quick response. I haven't looked to see how this gem utilizes the Her gem, but I am wondering the priority and estimated timeframe to remove Her. Know that I am a programmer as well and understand the difficulty of estimating.

**Comment by ryanswood** [comment]
@brissmyr @filiptepper ^^. Input would be appreciated.

**Comment by brissmyr** [comment]
Hey Ryan! I totally dropped this, sorry. Unfortunately, we will probably not be able to launch this before Rails 5 goes final. As much as we would like to do this right away, we don't have any developers available for the next couple of weeks. I will publish a request for assistance today to see if someone might be able to help out. I'll keep you posted.

**Comment by brissmyr** [comment]
Hi again Ryan. We've now put out a request for someone to help us on this one. Sorry for the wait!

**Comment by ryanswood** [comment]
@brissmyr Thank you for the update. Looking forward to further updates.

**Comment by ryanswood** [comment]
@brissmyr It has been some time since I last checked in. How have things progressed? FYI, Rails 5 has been released. https://twitter.com/dhh/status/748633781096026113

**Comment by filiptepper** [comment]
@ryanswood We've just cut 1.3.0 that should be compatible with Rails 5. There's also a new release of `devise_castle`. Let me know if you have any questions or issues.
