### ISSUE TITLE
Feature Request: Add support for multiple API environments

### ISSUE THREAD

**Issue by tommling** [castle/castle-ruby#161]
Consider the following:
Company A has a monolithic code base that serves more than one type of users that operate on the same data layer.
E.g.
- Admins
- Researchers
- Customers
They want to implement account takeover prevention, but they want to serve each different type of user a different flow. 

It would be great if castle could support multiple API environments. So that Admin events could go to one environment and Researchers could be sent to another.

**Comment by joladev** [comment]
Hey! This is a great suggestion and it's something we've been discussing internally. I can't give you an ETA on this since it's a significant change, but it's something we want to do.

**Comment by bartes** [comment]
hi @tommling - we are in process of releasing new powerful functionality for our product which will allow you to configure different flows per defined segments/scenarios within the dashboard. This should cover your case without a need of multiplying the api key. Please follow our https://blog.castle.io or https://twitter.com/castle_io for an updates regarding this.

**Comment by bartes** [comment]
hi @tommling - we are in process of releasing new powerful functionality for our product which will allow you to configure different flows per defined segments/scenarios within the dashboard. This should cover your case without a need of multiplying the api key. Please follow our https://blog.castle.io or https://twitter.com/castle_io for an updates regarding this.
