### ISSUE TITLE
`X-Castle-Request-Token` missing from `DEFAULT_ALLOWLIST`

### ISSUE THREAD

**Issue by bradymholt** [castle/castle-ruby#252]
In line with the [new API endpoints](https://docs.castle.io/docs/migrating-from-legacy-apis#step-2-passing-the-request-token-to-the-legacy-apis), shouldn't [Castle ::Configuration::DEFAULT_ALLOWLIST](https://github.com/castle/castle-ruby/blob/develop/lib/castle/configuration.rb#L48) contain the `X-Castle-Request-Token` header, since the [mobile SDK docs](https://docs.castle.io/docs/sdk-ios) mention it?

**Comment by bartes** [comment]
Thanks for pointing that out.

We are actually dropping X-Castle-Client-Id from the allowlist (https://github.com/castle/castle-ruby/pull/254), none of those X-Castle headers needs to be present there
